import { expect, test } from '@playwright/test';

test('setup and timer are separate screens throughout a complete timer', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-21T08:00:00Z') });
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('./');
  await expect(page.getByRole('heading', { name: '時間を設定' })).toBeVisible();
  await expect(page.locator('#timer-screen')).toBeHidden();
  await expect(page.locator('.garden')).toBeHidden();
  await page.getByRole('spinbutton').fill('2');
  await page.getByRole('button', { name: '開始', exact: true }).click();
  await expect(page).toHaveURL(/#timer$/);
  await expect(page.locator('#setup-screen')).toBeHidden();
  await expect(page.locator('#timer-screen')).toBeVisible();
  await expect(page.getByRole('spinbutton')).toHaveCount(0);
  await expect(page.locator('#timer-heading')).toBeFocused();
  await expect(page.getByRole('timer')).toHaveText('02:00');
  await expect(page.locator('.apple-slot')).toHaveCount(2);
  await page.clock.fastForward(59_000);
  await expect(page.locator('.is-eaten')).toHaveCount(0);
  await expect(page.locator('#apple-0 circle')).toHaveCount(9);
  await page.clock.fastForward(1_000);
  await expect(page.locator('.is-eaten')).toHaveCount(1);
  await expect(page.getByRole('timer')).toHaveText('01:00');
  await page.getByRole('button', { name: '一時停止', exact: true }).click();
  await page.clock.fastForward(90_000);
  await expect(page.getByRole('timer')).toHaveText('01:00');
  await expect(page.locator('#setup-screen')).toBeHidden();
  await page.getByRole('button', { name: '再開', exact: true }).click();
  await page.clock.fastForward(60_000);
  await expect(page.getByRole('timer')).toHaveText('00:00');
  await expect(page.locator('.is-eaten')).toHaveCount(2);
  await expect(page.locator('#status')).toHaveText('終了');
  await page.getByRole('button', { name: 'もう一度', exact: true }).click();
  await expect(page.getByRole('timer')).toHaveText('02:00');
  await page.getByRole('button', { name: '時間を変更', exact: true }).click();
  await expect(page.locator('#timer-screen')).toBeHidden();
  await expect(page.getByRole('spinbutton')).toHaveValue('2');
  await expect(page.locator('#setup-heading')).toBeFocused();
  expect(errors).toEqual([]);
});

test('iPhone navigation, duration limits, automatic scroll, and mute', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 });
  await page.clock.install({ time: new Date('2026-09-21T08:00:00Z') });
  await page.goto('./');
  await page.getByRole('spinbutton').fill('99');
  await page.getByRole('spinbutton').press('Tab');
  await expect(page.getByRole('spinbutton')).toHaveValue('60');
  await page.getByRole('button', { name: 'お知らせの音' }).click();
  await expect(page.getByRole('button', { name: 'お知らせの音' })).toHaveAttribute('aria-pressed', 'false');
  await page.getByRole('button', { name: '開始', exact: true }).click();
  await expect(page.locator('.apple-slot')).toHaveCount(60);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.clock.fastForward(10 * 60_000);
  await expect(page.locator('.is-eaten')).toHaveCount(10);
  expect(await page.locator('#apple-scroll').evaluate((element) => element.scrollTop)).toBeGreaterThan(0);
  await page.goBack();
  await expect(page.locator('#timer-screen')).toBeHidden();
  await expect(page.getByRole('spinbutton')).toHaveValue('60');
  await page.goForward();
  await expect(page.locator('#timer-screen')).toBeHidden();
  await expect(page).not.toHaveURL(/#timer$/);
  await page.clock.fastForward(60_000);
  await page.getByRole('spinbutton').fill('0');
  await page.getByRole('spinbutton').press('Tab');
  await expect(page.getByRole('spinbutton')).toHaveValue('1');
  await page.getByRole('button', { name: '5分', exact: true }).click();
  await page.getByRole('button', { name: '開始', exact: true }).click();
  await expect(page.getByRole('timer')).toHaveText('05:00');
  await expect(page.locator('.is-eaten')).toHaveCount(0);
  await page.reload();
  await expect(page.locator('#timer-screen')).toBeHidden();
  await expect(page.getByRole('heading', { name: '時間を設定' })).toBeVisible();
});

test('both screens fit mobile and desktop without horizontal overflow', async ({ page }) => {
  await page.goto('./');
  await page.evaluate(() => document.fonts.ready);
  for (const [name, width, height] of [['desktop', 1440, 1000], ['iphone', 390, 844], ['small-iphone', 320, 568]] as const) {
    await page.setViewportSize({ width, height });
    await page.screenshot({ path: `test-results/${name}-setup.png`, fullPage: true, animations: 'disabled' });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.getByRole('button', { name: '開始', exact: true }).click();
    await expect(page.locator('#setup-screen')).toBeHidden();
    await expect(page.getByRole('button', { name: '一時停止', exact: true })).toBeInViewport();
    await page.screenshot({ path: `test-results/${name}-timer.png`, fullPage: true, animations: 'disabled' });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    const applePositions = await page.locator('.apple-slot').evaluateAll((apples) => apples.map((apple) => apple.getBoundingClientRect().top));
    expect(applePositions[3]).toBeGreaterThan(applePositions[0]);
    await page.getByRole('button', { name: '時間を変更', exact: true }).click();
    await expect(page.getByRole('button', { name: '開始', exact: true })).toBeVisible();
  }
});
